### ISSUE TITLE
Feature request: Add support for tagging resources

### ISSUE THREAD

**Issue by sigismund** [scastria/terraform-provider-konnect#5]
First off, huge thanks for your work on this provider—it’s been a game changer compared to the official one.

It’s pretty much all great, but I’ve noticed we can’t tag resources. It would be super helpful for managing and organizing everything if we could add tags to resources that support them.

**Quick Details**

- Feature Needed: Ability to add custom tags to resources.
- Why It Matters: Helps with sorting and managing resources, especially when dealing with multiple environments like 'production' or 'development'.

**Questions**

- Any technical reasons this isn’t possible yet?
- Or maybe plans to add this feature in the future?

Thanks!

**Comment by scastria** [comment]
Thanks.  I have my own issues with the official one.  I am curious why you don't like the official provider?

No reason why tags aren't there, just didn't have a need myself.  I looked into tags at one point 2 years ago and the Konnect API did not implement them all the same which makes it harder on me to support them.  Let me look again and I will see what I can do.  My plan 2 years ago was to implement it like AWS provider.  The AWS provider allows you to specify default tags in the provider configuration itself and those get applied to all resources automatically UNLESS you specify tags for a specific resource and then those can override the default tags.
